import { Injectable, Output } from '@angular/core';
import { EventEmitter } from 'events';

@Injectable()
export class NavigationService {
  @Output() footerNav = new EventEmitter();
  footerNavListArr: any;
  /* tslint:disable */
  globalObject = {
    "request": {
      "culture": "es-ES",
      "host": "www.betway.lat.dv",
      "device": {
        "browser": "Unknown",
        "OS": "Unknown",
        "isMobile": false,
        "isTablet": false
      }
    },
    "variables": {
      "cms": "http://cms1.gmgamingsystems.com.dv",
      "cdn": "http://cdn.gmgamingsystems.com.dev.labenv",
      "api": "http://api.gmgamingsystems.com.dev.labenv",
      "apic": "http://apic.gmgamingsystems.com.dev.labenv"
    },
    "sitemap": [
      {
        "P": "/Casa/",
        "C": "Casa",
        "PN": "Home",
        "A": "Home",
        "DMC": "",
        "PG": "9a3b4846-12b0-45c2-9688-09d4a2e29fdc",
        "TN": true,
        "SM": true,
        "FN": false,
        "PD": "Regístrate en Betway ahora mismo y recibe nuestro estupendo bono de bienvenida para nuevos clientes de 150% hasta $60. Betway es la mejor plataforma de apuestas deportivas online.",
        "PKW": null,
        "MID": "",
        "MC": "Casa",
        "PT": "Apuesta online en tu deporte favorito con Betway | Abre una cuenta",
        "CH": [],
        "M": "Unmapped",
        "T": "MenuItem",
        "CN": "Class"
      },
      {
        "P": "/regstependes/",
        "C": "Reg Step End Offer",
        "PN": "Reg Step End Offer",
        "A": "Reg-Step-End-Offer",
        "DMC": "",
        "PG": "e6023c72-b7e7-42d7-aafc-df5e696c1d13",
        "TN": false,
        "SM": false,
        "FN": false,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Reg Step End Offer",
        "PT": null,
        "CH": [],
        "M": "Unmapped",
        "T": "MenuItem",
        "CN": "Class"
      },
      {
        "P": "/deportes/",
        "C": "Deportes",
        "PN": "Sports",
        "A": "Sports",
        "DMC": "",
        "PG": "fcc4450f-44a4-4f66-81e6-75fd6c6ee6a4",
        "TN": true,
        "SM": true,
        "FN": false,
        "PD": "Regístrate en Betway ahora mismo y recibe nuestro estupendo bono de bienvenida del 150% para nuevos clientes hasta $60. Betway es la mejor plataforma de apuestas deportivas online.",
        "PKW": null,
        "MID": "theme-Sports",
        "MC": "Deportes",
        "PT": "Apuesta online en tu deporte favorito con Betway | Abre una cuenta",
        "CH": [
          {
            "P": "/deportes/futbol/",
            "C": "Fútbol",
            "PN": "Football",
            "A": "Football",
            "DMC": "",
            "PG": "66155551-b9bb-47e0-8a87-f869ad1f4eda",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "Haz tus apuestas deportivas en Betway y sácale el mayor provecho a tu dinero y disfruta de una experiencia inigualable. ",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Fútbol",
            "PT": "Haz tus apuestas de fútbol en Betway l Apoya a tu equipo favorito",
            "CH": [
              {
                "P": "/deportes/futbol/la-liga/",
                "C": "La Liga",
                "PN": "La Liga",
                "A": "La-Liga",
                "DMC": "",
                "PG": "62a4f634-8a60-4f11-ba8e-a9f2a709a79f",
                "TN": true,
                "SM": true,
                "FN": false,
                "PD": "Talento de alto nivel, mucha competición entre equipos,  y el espectáculo de sus estrellas hacen de la Liga la mejor del mundo. ¡Haz tus apuestas deportivas online y mete gol de media cancha con Betway!",
                "PKW": null,
                "MID": "theme-Sports",
                "MC": "La Liga",
                "PT": "Haz tus apuestas de fútbol en Betway l Apoya a tu equipo favorito",
                "CH": [],
                "M": "AppComponent",
                "T": "ComponentMenuItem",
                "CN": "Class"
              },
              {
                "P": "/deportes/futbol/liga-de-campeones/",
                "C": "Liga de Campeones",
                "PN": "Championship League",
                "A": "Champions-League",
                "DMC": "",
                "PG": "9e84e164-8851-4649-a106-0739c0b8c51f",
                "TN": true,
                "SM": true,
                "FN": false,
                "PD": "La final de la UEFA Champions League es el evento deportivo anual más visto en el mundo y Betway te la pone en bandeja. ",
                "PKW": null,
                "MID": "theme-Sports",
                "MC": "Liga de Campeones",
                "PT": "La Liga de Campeones (UEFA) l Encuéntrala en Betway",
                "CH": [],
                "M": "AppComponent",
                "T": "ComponentMenuItem",
                "CN": "Class"
              },
              {
                "P": "/deportes/futbol/copa-libertadores/",
                "C": "Copa Libertadores",
                "PN": "Copa Libertadores",
                "A": "Copa-Libertadores",
                "DMC": "",
                "PG": "0cedd053-da69-437d-8725-d61f7d3f2301",
                "TN": true,
                "SM": true,
                "FN": false,
                "PD": "En Latinoamérica vivimos y respiramos fútbol y no hay mejor lugar para celebrar nuestro amor por el juego que en una final de la Copa Libertadores. ",
                "PKW": null,
                "MID": "theme-Sports",
                "MC": "Copa Libertadores",
                "PT": "Apuesta al fútbol y apoya a tu equipo favorito l Realiza tus apuestas en Betway",
                "CH": [],
                "M": "AppComponent",
                "T": "ComponentMenuItem",
                "CN": "Class"
              },
              {
                "P": "/deportes/futbol/epl/",
                "C": "EPL",
                "PN": "EPL",
                "A": "EPL",
                "DMC": "",
                "PG": "ccc16a7c-0fef-49b4-9b18-113ff162ed60",
                "TN": true,
                "SM": true,
                "FN": false,
                "PD": "Premier League inglesa (EPL) considerada, por muchos, la mejor liga de fútbol del mundo. ",
                "PKW": null,
                "MID": "theme-Sports",
                "MC": "EPL",
                "PT": "Premier League inglesa l Haz tus apuestas en Betway",
                "CH": [],
                "M": "AppComponent",
                "T": "ComponentMenuItem",
                "CN": "Class"
              }
            ],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/deportes/beisbol/",
            "C": "Béisbol",
            "PN": "Baseball",
            "A": "baseball",
            "DMC": "",
            "PG": "1d92f6d9-a404-451c-9679-40bf2d21576e",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "El béisbol es un deporte súper emocionante, ¡compruébalo con nosotros! Haz tus apuestas en Betway",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Béisbol",
            "PT": "Apuesta al béisbol en Betway l Apuestas a ganador",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/deportes/basquetbol/",
            "C": "Básquetbol",
            "PN": "Basketball",
            "A": "basketball",
            "DMC": "",
            "PG": "1c66066f-2855-4fb4-a554-fbc478b3ca26",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "El básquetbol es uno de los deportes más practicados en América del Norte y Betway es el líder en apuestas <i>online</i>",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Básquetbol",
            "PT": "Apuesta al básquetbol en Betway ",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/deportes/golf/",
            "C": "Golf",
            "PN": "Golf",
            "A": "Golf",
            "DMC": "",
            "PG": "e427aa28-9228-4e5f-924a-e062bf151acf",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "Lanza la bola hacia grandes victorias con tus apuestas de golf. En Betway tenemos las mejores cuotas y los principales eventos deportivos.",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Golf",
            "PT": "Apuesta al golf l Apuesta en Betway",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/deportes/hockey-sobre-hielo/",
            "C": "Hockey Sobre Hielo",
            "PN": "Ice Hockey",
            "A": "ice-hockey",
            "DMC": "",
            "PG": "11ec7414-96e4-4c17-9038-b805cef2cd2a",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "Comienza a apostar en las ligas de hockey sobre hielo más populares del mundo en la casa de apuestas deportivas Betway. Ofrecemos cuotas muy competitivas en ligas de muchos países incluyendo NHL, VHL, KHL y la extra liga checa.",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Hockey Sobre Hielo",
            "PT": "Hockey sobre hielo | Apuestas deportivas online Betway",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/deportes/formula/",
            "C": "Fórmula 1",
            "PN": "Formula 1",
            "A": "Formula",
            "DMC": "",
            "PG": "cd5ce35d-63ae-41fe-bb48-bb26e39e6db3",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "Apuesta por los grandes pilotos de Fórmula 1 Gran Premio de Mónaco y otras grandes competencias automovilísticas y deportivas. Coloca tus apuestas y gana con Betway.",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Fórmula 1",
            "PT": "La emoción de la Fórmula 1 l Haz tus apuestas en Betway ",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/deportes/apuestas-en-vivo/",
            "C": "Apuestas en vivo",
            "PN": "Live Bettting",
            "A": "Live-Betting",
            "DMC": "",
            "PG": "8a0e39b7-f1eb-4f94-af6f-3579325f94b5",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "Apuesta al fútbol, tenis, baloncesto o a otro deporte de tu elección. Coloca tus apuestas en diversos torneos, ligas y competencias llenas de emoción con Betway.",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Apuestas en vivo",
            "PT": "Haz tus apuestas en vivo, apuesta por tu deporte favorito en Betway ",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/deportes/rugby/",
            "C": "Rugby",
            "PN": "Rugby",
            "A": "Rugby",
            "DMC": "",
            "PG": "b1294c22-1270-42ea-b6ac-25e25a3707aa",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "Place wagers on rugby fixtures online from around the world at Betway online sports betting. We offer the best odds on fixtures from the Sothern Hemisphere’s Super Rugby league to the Northern Hemisphere’s six nations and more.",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Rugby",
            "PT": "Bet on rugby online | Betway Online Sports Betting",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/deportes/tenis/",
            "C": "Tenis",
            "PN": "Tennis",
            "A": "Tennis",
            "DMC": "",
            "PG": "2e4ba933-49a9-4dcd-99fa-bbc12093b440",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "El tenis es uno de los deportes más populares en el mundo y Betway te ofrece la oportunidad de disfrutar de competencias internacionales como Wimbledon y Roland Garros mientras haces tus apuestas.",
            "PKW": null,
            "MID": "theme-Sports",
            "MC": "Tenis",
            "PT": "Apuesta al tenis con Betway l Forma parte del equipo ganador",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          }
        ],
        "M": "Unmapped",
        "T": "MenuItem",
        "CN": "Class"
      },
      {
        "P": "/casino-casa/",
        "C": "Casino",
        "PN": "Casino",
        "A": "Casino",
        "DMC": "",
        "PG": "744a65aa-2aa8-4831-9c0e-f9c220efabbe",
        "TN": true,
        "SM": true,
        "FN": false,
        "PD": null,
        "PKW": null,
        "MID": "GCID-0790e4d3-74a8-47f2-b255-a22496d8681f",
        "MC": "Casino",
        "PT": null,
        "CH": [
          {
            "P": "/casino-casa/juegos-de-mesa/",
            "C": "Juegos de mesa",
            "PN": "Table Games",
            "A": "Table-Games",
            "DMC": "",
            "PG": "fa0cbaaa-a1ce-4268-a83d-991216e8898f",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "¿Quieres probar tu suerte y divertirte al mismo tiempo? Toma asiento en una de nuestras mesas en línea o de nuestro “casino en vivo” ",
            "PKW": null,
            "MID": "GCID-312c419d-e3f4-4c51-b575-26810d88e5ca, theme-Casino",
            "MC": "Juegos de mesa",
            "PT": "Juega a los juegos de mesa con Betway | Gánale al crupier",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/casino-casa/tragamonedas/",
            "C": "Tragamonedas",
            "PN": "Slots",
            "A": "Slots",
            "DMC": "",
            "PG": "e8da2394-9211-45b9-a0e5-2b58c8dd5eca",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "Si estás buscando los mejores juegos de tragamonedas, ¡ya los encontraste! Betway casino ofrece una gran variedad de  tragamonedas de 5 y 3 carretes, al igual que tragamonedas clásicas y progresivas.",
            "PKW": null,
            "MID": "GCID-cb3a1eb4-2c9c-4c23-80ce-500a566b1222, theme-Casino",
            "MC": "Tragamonedas",
            "PT": "Tragamonedas, el juego de casino en línea favorito | Juega en Betway",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/casino-casa/video-poker/",
            "C": "Vídeo Póker",
            "PN": "Video Poker",
            "A": "Video-poker",
            "DMC": "",
            "PG": "00effa85-707a-425b-888b-dd516c1940e5",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "¿Estás listo para tener horas interminables de diversión y emoción? Betway te ofrece la opción de elegir entre video póker individual o multi-juego, lo que hace que el póker sea mucho más interesante.",
            "PKW": null,
            "MID": "GCID-c2612a83-158e-479e-a88a-4a3c1c1e4c49, theme-Casino",
            "MC": "Vídeo Póker",
            "PT": "¡Juega a video póker | Siente la emoción con Betway!",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/casino-casa/juegos-progresivos/",
            "C": "Juegos Progresivos",
            "PN": "Progressives",
            "A": "Progressives",
            "DMC": "",
            "PG": "acd38282-486b-48ed-8b06-69db29b78657",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "Si lo que buscas es la emoción de sentir que puedes ganar el premio gordo, entonces llegaste al lugar adecuado. Betway ofrece una amplia variedad de juegos progresivos con premios que alcanzan los millones. ",
            "PKW": null,
            "MID": "GCID-e7c2387a-c75f-417c-b964-c7abae959cdb, \r\ntheme-Casino",
            "MC": "Juegos Progresivos",
            "PT": "Pozos progresivos en Betway l Atrévete a jugarlos, haz tus apuestas",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          }
        ],
        "M": "Unmapped",
        "T": "MenuItem",
        "CN": "Class"
      },
      {
        "P": "/casino-en-vivo/",
        "C": "Casino en vivo",
        "PN": "Live Casino",
        "A": "Live-Casino",
        "DMC": "",
        "PG": "c8ba4051-beee-44f8-b5d7-3f18a5122dbe",
        "TN": true,
        "SM": true,
        "FN": false,
        "PD": null,
        "PKW": null,
        "MID": "GCID-5e95eb87-c4a5-4b1b-b027-5b1c2068251c",
        "MC": "Casino en vivo",
        "PT": null,
        "CH": [],
        "M": "Unmapped",
        "T": "MenuItem",
        "CN": "Class"
      },
      {
        "P": "/in-play-casa/",
        "C": "En Vivo",
        "PN": "In-Play",
        "A": "InPlay",
        "DMC": "",
        "PG": "ed66d3c2-b590-4ef1-9dc5-c76b190c9ddc",
        "TN": true,
        "SM": true,
        "FN": false,
        "PD": "Comparte la emoción de las apuestas deportivas en directo online y disfruta cada momento de tu deporte favorito. Haz tu apuesta en directo en fútbol, baloncesto, hockey y mucho más.",
        "PKW": null,
        "MID": "",
        "MC": "En Vivo",
        "PT": "Betway | Apuestas deportivas online en directo ",
        "CH": [],
        "M": "Unmapped",
        "T": "MenuItem",
        "CN": "Class"
      },
      {
        "P": "/vegas-casa/",
        "C": "Vegas",
        "PN": "Vegas",
        "A": "Vegas",
        "DMC": "",
        "PG": "b2af8046-17cd-43e5-ae2c-f4209b45c8bb",
        "TN": true,
        "SM": true,
        "FN": false,
        "PD": "Lleva tu juego al próximo nivel en el casino en línea Betway con la excelente selección de tragamonedas diseñada por el proveedor líder de juegos de casino online, NetEnt.",
        "PKW": null,
        "MID": "GCID-6b4352b4-59d9-4651-83d6-7bdce3ebc64e ",
        "MC": "Vegas",
        "PT": "Juegos de casino NetEnt | Betway ",
        "CH": [],
        "M": "Unmapped",
        "T": "MenuItem",
        "CN": "Class"
      },
      {
        "P": "/OffersES/",
        "C": "Offers",
        "PN": "Offers",
        "A": "Offers",
        "DMC": "",
        "PG": "c964cdca-5d4d-42ac-ab83-10245b65ffce",
        "TN": false,
        "SM": false,
        "FN": false,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Offers",
        "PT": null,
        "CH": [],
        "M": "Unmapped",
        "T": "Folder",
        "CN": "Class"
      },
      {
        "P": "/promotionblockses/",
        "C": "PromotionBlocks",
        "PN": "PromotionBlocks",
        "A": "Promotion-Blocks",
        "DMC": "",
        "PG": "54f7a09f-d46d-4772-8fc8-5f9fdc80119c",
        "TN": false,
        "SM": false,
        "FN": false,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "PromotionBlocks",
        "PT": null,
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/terminos/",
        "C": "Términos y condiciones",
        "PN": "Terms",
        "A": "terms",
        "DMC": "",
        "PG": "b41d3403-d702-4c41-ad45-be5e5243a739",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "redirect-a-general-terms",
        "MC": "Términos y condiciones",
        "PT": "Términos y condiciones generales",
        "CH": [
          {
            "P": "/terminos/terminos-generales/",
            "C": "Términos Generales",
            "PN": "General T&Cs",
            "A": "general-terms",
            "DMC": "",
            "PG": "555a852f-d770-4bde-9ec0-3eaf5166d2c6",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": null,
            "PKW": null,
            "MID": "",
            "MC": "Términos Generales",
            "PT": null,
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/terminos/promociones-terminos/",
            "C": "Términos y promociones",
            "PN": "Promotional T&Cs",
            "A": "promo-terms",
            "DMC": "",
            "PG": "00effc90-9611-4ee1-bcd7-73840245d4ac",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": null,
            "PKW": null,
            "MID": "",
            "MC": "Términos y promociones",
            "PT": null,
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/terminos/retiros/",
            "C": "Términos y Retiros",
            "PN": "Withdrawal T&Cs",
            "A": "Withdrawals-terms",
            "DMC": "",
            "PG": "5e87795a-500e-4776-8cb9-43bdb208a4f4",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "",
            "PKW": null,
            "MID": "",
            "MC": "Términos y Retiros",
            "PT": "",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/terminos/depositos/",
            "C": "Términos y depósitos",
            "PN": "Deposit Bonus",
            "A": "Deposit-Bonus-terms",
            "DMC": "",
            "PG": "5308b7f2-c34f-4033-a526-9381853307dc",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "",
            "PKW": null,
            "MID": "",
            "MC": "Términos y depósitos",
            "PT": "",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/terminos/bono-de-bienvenida/",
            "C": "Bono de bienvenida Casino",
            "PN": "Welcome Bonus Casino",
            "A": "Welcome-Bonus-terms",
            "DMC": "",
            "PG": "fc77d947-9f83-420e-a91d-c105b2c9eb1c",
            "TN": true,
            "SM": true,
            "FN": false,
            "PD": "",
            "PKW": null,
            "MID": "",
            "MC": "Bono de bienvenida Casino",
            "PT": "",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          },
          {
            "P": "/terminos/bono-de-bienvenida-deportes/",
            "C": "Bono de bienvenida deportes",
            "PN": "Welcome Bonus Sports",
            "A": "Welcome-Bonus-sport-terms",
            "DMC": "",
            "PG": "bb4237c5-6787-4d8c-9187-4389198747d9",
            "TN": false,
            "SM": true,
            "FN": false,
            "PD": "",
            "PKW": null,
            "MID": "",
            "MC": "Bono de bienvenida deportes",
            "PT": "",
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          }
        ],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/reglas-de-apuestas/",
        "C": "Reglas de apuestas",
        "PN": "Betting rules",
        "A": "betting-rules",
        "DMC": "",
        "PG": "578ec689-42c5-4369-9fce-9bbdfe15c90c",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Reglas de apuestas",
        "PT": "Reglas generales de apuestas deportivas",
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/retiro-anticipado/",
        "C": "Retiro Anticipado",
        "PN": "Cash Out Rules",
        "A": "cash-out-rules",
        "DMC": "",
        "PG": "f60e3276-99b8-4849-ba56-41c43fa30e3a",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Retiro Anticipado",
        "PT": null,
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/preguntas-frecuentes/",
        "C": "Preguntas frecuentes",
        "PN": "FAQs",
        "A": "FAQs",
        "DMC": "",
        "PG": "94cb6e49-6707-4d2a-92db-846efd03714c",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": "¿Quiénes somos? ¿Qué hacemos? ¿Qué es una cuota? Recibimos muchas preguntas y las respondemos gustosamente a fin de darte la seguridad que necesitas antes de que abras una cuenta en una casa de apuestas deportivas y de que apuestes tu dinero con nosotros. ",
        "PKW": null,
        "MID": "",
        "MC": "Preguntas frecuentes",
        "PT": "Respuestas a las preguntas más frecuentes sobre apuestas online",
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/privacidad/",
        "C": "Privacidad y seguridad",
        "PN": "Privacy and Security",
        "A": "Privacy-and-Security",
        "DMC": "",
        "PG": "0e9fa092-dd61-40fe-8740-5f6dbb0073d1",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Privacidad y seguridad",
        "PT": "Política de privacidad de Betway",
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/juego-responsable/",
        "C": "Juego responsable",
        "PN": "Responsible Gaming",
        "A": "Responsible-Gaming",
        "DMC": "",
        "PG": "139b0974-be13-4aeb-86c4-128f26175b23",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Juego responsable",
        "PT": "Juego responsable",
        "CH": [
          {
            "P": "/juego-responsable/auto-evaluacion/",
            "C": "Auto evaluación",
            "PN": "Self Assessment",
            "A": "Self-Assessment",
            "DMC": "",
            "PG": "2f98c25d-3c29-4793-a21e-285a27c66675",
            "TN": false,
            "SM": false,
            "FN": false,
            "PD": null,
            "PKW": null,
            "MID": "",
            "MC": "Auto evaluación",
            "PT": null,
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          }
        ],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/mapa/",
        "C": "Mapa del sitio",
        "PN": "Sitemap",
        "A": "Sitemap",
        "DMC": "",
        "PG": "237f5188-a86c-44fa-8f9b-16bb1140b206",
        "TN": false,
        "SM": false,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Mapa del sitio",
        "PT": null,
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/preferencias-subscripcion/",
        "C": "Preferencias subscripcion",
        "PN": "Subscribe/Unsubscribe",
        "A": "Subscribe-Unsubscribe",
        "DMC": "",
        "PG": "9c69c236-c90c-4483-ba56-b872c426ed1a",
        "TN": false,
        "SM": false,
        "FN": false,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Preferencias subscripcion",
        "PT": null,
        "CH": [
          {
            "P": "/confirmacion-de-baja/",
            "C": "Confirmación de baja",
            "PN": "Unsubscribe Verification",
            "A": "Unsubscribe-Verification",
            "DMC": "",
            "PG": "c2045487-f7f6-4965-8eb9-bf27c3e9e9c4",
            "TN": false,
            "SM": false,
            "FN": false,
            "PD": null,
            "PKW": null,
            "MID": "",
            "MC": "Confirmación de baja",
            "PT": null,
            "CH": [],
            "M": "AppComponent",
            "T": "ComponentMenuItem",
            "CN": "Class"
          }
        ],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/promociones/",
        "C": "Promociones",
        "PN": "Promotions",
        "A": "Promotions-Page",
        "DMC": "",
        "PG": "ba045bfd-3678-4359-81f0-15292c8aefd5",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Promociones",
        "PT": null,
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/sobre-nosotros/",
        "C": "Nosotros",
        "PN": "About us",
        "A": "About-us",
        "DMC": "",
        "PG": "368f60dd-3d67-43e7-826b-f5aa7effee74",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": "Si estás buscando la mejor opción para colocar tus apuestas deportivas online, ¡ya la encontraste con Betway!  ",
        "PKW": null,
        "MID": "",
        "MC": "Nosotros",
        "PT": "Betway: realiza tus apuestas deportivas online. Vive cada minuto de la acción con nosotros.",
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/comenzar/",
        "C": "Cómo comenzar",
        "PN": "Getting Started",
        "A": "getting-started",
        "DMC": "",
        "PG": "2b3b4c4f-a2e1-463c-9b5c-240cbcbf9969",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": "¿Qué esperas para formar parte del equipo ganador? Abriendo tu cuenta en Betway tendrás acceso a toda la exaltación y a la pasión del mundo deportivo. Diviértete colocando tus apuestas deportivas",
        "PKW": null,
        "MID": "",
        "MC": "Cómo comenzar",
        "PT": "¡Qué comience la emoción y la diversión: haz tus apuestas con Betway! ",
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/contactenos/",
        "C": "Contáctanos",
        "PN": "Contact Us",
        "A": "Contact-Us",
        "DMC": "",
        "PG": "3bc73b54-961d-4840-a880-512951204dd1",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Contáctanos",
        "PT": null,
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/banca/",
        "C": "Banca",
        "PN": "Banking",
        "A": "Banking",
        "DMC": "",
        "PG": "56e9827c-3fcf-44dd-8613-1311efcd47cb",
        "TN": true,
        "SM": true,
        "FN": true,
        "PD": null,
        "PKW": null,
        "MID": "",
        "MC": "Banca",
        "PT": null,
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      },
      {
        "P": "/404/",
        "C": "404",
        "PN": "404",
        "A": "404",
        "DMC": "",
        "PG": "a64e55e3-5391-4e97-83cd-a24c1b31d7c2",
        "TN": false,
        "SM": false,
        "FN": false,
        "PD": "The page you’re looking for could not be found. Please navigate back to the homepage and try again.",
        "PKW": null,
        "MID": "",
        "MC": "404",
        "PT": "404 Page Error | Betway",
        "CH": [],
        "M": "AppComponent",
        "T": "ComponentMenuItem",
        "CN": "Class"
      }
    ]
  };
  siteMapObject = this.globalObject.sitemap;
  constructor() { }

  ngOnInit() {
    // this.SiteMapURL = this.sitemap.filter((value) => { if (value.A === 'Sitemap') { return value; } });
    // this.contentSrvc.getContentByGuid(this.SiteMapURL[0].PG).subscribe(res => {
    //     this.siteMapHeading = res['WP'][0].WPC;
    // });
  }

  getFooterNav() {
    this.footerNavListArr = this.siteMapObject.filter((value) => {
      return value.FN;
    });
    return this.footerNavListArr;
  }

}
